# Generated by Django 5.1.2 on 2025-03-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route_instruction',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='total_distance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
