# Generated by Django 5.1.2 on 2025-03-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_route_instruction_trip_total_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='route_instruction',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='total_distance',
        ),
    ]
